apiVersion: v1
kind: Pod
metadata:
  name: pod-inti-container
spec:
  intiContainers:
    - name:  debug
      image: docker.io/rkalluru/learnk8s:init-container-html-generator
      volumeMounts:
        - mountPath: /mnt/html
          name: html
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
  volumes:              #using common storage here & using mount in line 9 & 14
    - name: html
      emptyDir: {}